sources:
  - name: Trident
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:sushi-qa/trident-optimism}
    transforms:
      - autoPagination:
          validateSchema: true
  - name: V2
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:sameepsi/quickswap06}
        retry: 3
    transforms:
      - prefix:
          value: V2_
          includeRootOperations: true
          includeTypes: true
      # - autoPagination:
      #     validateSchema: true   
  - name: V3
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:uniswap/uniswap-v3}
        retry: 3
    transforms:
      - prefix:
          value: V3_
          includeRootOperations: true
          includeTypes: true
  - name: MasterChef
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sushiswap/masterchef-v2-ethereum
    transforms:
      - prefix:
          value: MasterChef_
          includeRootOperations: true
          includeTypes: true
  - name: MiniChef
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com/subgraphs/name}/{context.name:jiro-ono/minichef-staging-updates}
    transforms:
      - prefix:
          value: MiniChef_
          includeRootOperations: true
          includeTypes: true
documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { name: string; host: string; path: string; }'

